version: '3'
services:
  app:
    build: .
    working_dir: /app
    command: ["./myapp"]
    # volumes:
      # - .:/app
    ports:
      - "8080:8080"
      
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: jeter
      MYSQL_DATABASE: chat
      MYSQL_USER: jeter
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    # volumes:
      # - mysql_data:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:6
    container_name: redis
    command: ["redis-server", "--requirepass", "jeter"]
    ports:
      - "6379:6379"
    # volumes:
      # - redis_data:/data
    networks:
      - app_network

# volumes:
  # mysql_data:
    # driver: local
    # driver_opts:
      # type: none
      # o: bind
      # device: /mnt/c/Users/jeter_hsu/Desktop/docker/mysql
  # redis_data:
    # driver: local
    # driver_opts:
      # type: none
      # o: bind
      # device: /mnt/c/Users/jeter_hsu/Desktop/docker/redis

networks:
  app_network:
