redis:
#  Address: "redis:6379"
  Address: "127.0.0.1:6379"
  password: "jeter"
  db: 0
  pool_size: 10
  min_idle_conns: 3
  dial_timeout: 5
  read_timeout: 3
  write_timeout: 3

mysql:
  UserName: "root"
  Password: "jeter"
#  Address: "mysql"
  Address: "127.0.0.1"
  Port: 3306
  Database: "chat"
  MaxLifetime: 10
  MaxOpenConnections: 10
  MaxIdleConnections: 10

Jwt:
  SecretKey: "d86ecd989966768001ae86ac7069a699c15fe9b2cb10ee27f538cf36108c7a71"